name: custom_loader
description: Custom Loader
version: 0.0.1
homepage: https://github.com/huextrat/custom_loader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: